project_id = "tsyohnenxczynjuvgyrj"

[functions.send-email]
verify_jwt = true

[functions.payfast-webhook]
verify_jwt = false

[functions.ai-chatbot]
verify_jwt = false

[functions.assign-delivery-partner]
verify_jwt = true

[functions.send-push]
verify_jwt = true

[functions.seed-demo-data]
verify_jwt = false
